### ISSUE TITLE
[Enahncement] When linting, show me the summary of errors

### ISSUE THREAD

**Issue by jnv** [superfaceai/cli#203]
Currently when I lint in huge project, like [station](https://github.com/superfaceai/station), I get verbose, yet useless output (see eg. [here](https://github.com/superfaceai/station/runs/6325585597?check_suite_focus=true)): When there is an error with my files, at the end I get only this unhelpful message:

```
Detected 1 problem
 ›   Error: ❌ Errors were found
```

And I need to scroll back and search through the list of linted files to find my error.

My suggestion here is for CLI is to act like any sensitive linter / test harness out there, and display summary of errors at the end. Alternatively `lint` command could also display only errors instead of listing all the validated files, having a verbose switch to also display OK files – still, a summary of errors at the end would be nice nevertheless.

**Comment by Jakub-Vacek** [comment]
@jnv 
We already have `format` which can be used to define format/length of output. I an not sure tah new flag is needed 🤷🏻‍♂️

We could do like this:

`sf lint` => print only errors and warnings (format is `short` by default)
`sf lint -f long` => print everything and add error and warning summary

**Comment by jnv** [comment]
OK, agreed that a new flag is not necessary (or it could act as an alias to match the conventions), but that was not my primary issue.

**Comment by Jakub-Vacek** [comment]
Would you agree with the `sf lint` (only summary) and `sf lint -f long` (verbose + summary) solution? :)

**Comment by jnv** [comment]
I don't think that would work. If I understand it correctly, `sf lint` (without `-f`) is the default used on Station and the failed checks are hidden among other outputs.

I see the following options:

- Add new format option like "errors only" and set it as default and/or use it in Station
- Change the default format option to display only errors
- Summarize errors at the end of run regardless of the output format (personally preferred variant)

In addition to that, the summary at the end should display number of checked files. This is in general useful indicator for the user that the command did actually check anything.

**Comment by Jakub-Vacek** [comment]
@jnv Ok, so print of `sf lint -f long` looks like:

![Snímek obrazovky 2022-06-20 v 11 47 37](https://user-images.githubusercontent.com/21127441/174575327-b5c9b312-685f-48db-bde1-89e827f22005.png)


And for `sf lint`

![Snímek obrazovky 2022-06-20 v 11 48 47](https://user-images.githubusercontent.com/21127441/174575463-8e501f28-7541-46cd-8437-af563e1c3b58.png)

I think this is ok :)
