### ISSUE TITLE
[BUG] Deleting a provider after running `prepare`

### ISSUE THREAD

**Issue by martyndavies** [superfaceai/cli#309]
As a user, if I run `prepare` and create an initial set up for a provider, then I delete the `provider.json` from the Superface folder, I cannot continue to work with that provider. The server side provider exists, so a new local version cannot be created.

This results in a command loop that you can't get out of because the commands start to contradict each other:

![CleanShot 2023-07-07 at 14 41 48](https://github.com/superfaceai/cli/assets/16167/754ae7d9-60f6-43bb-9ce6-7996a4d244eb)

## Possible Solution
Perhaps a manual sync such as `superface sync provider notion` that would pull the server side version.

## Steps to Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
1. Run `prepare` on any documentation
2. Delete the provider file locally
3. Try to run `prepare` again

## Your Environment
CLI version 4.0.0-beta.3

**Comment by zdne** [comment]
FWIW The same happens if you move to another computer and login with as the same user...

**Comment by kysely** [comment]
This now works. If the Provider JSON definition isn't found locally, the CLI pulls it from the remote. Closing
