### ISSUE TITLE
[BUG] Communicate that I need to run superface execute from the superface folder

### ISSUE THREAD

**Issue by zdne** [superfaceai/cli#316]
Apparently I need to run `superface execute` from within the respective superface folder. If I don't I get a very misleading message:

```
% superface execute notion-alt notion-workspace/retrieve-users
Executing: "node --experimental-wasi-unstable-preview1 /Users/z/Codebase/superface/edgar-release/superface/notion-workspace.retrieve-users.notion-alt.mjs"
(node:33842) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR: {
  "name": "TakePerformInputError"
}
🆗 Child process exited with code 0
```

## Expected Behavior
If I am running the `execute` outside of the superface folder I get a message that I need to be in a superface folder. The example (.mjs) file is not executed and no OneSDK perform is attempted.

## Your Environment
- @superfaceai/cli/4.0.0-beta.5 darwin-x64 node-v18.13.0 (with @superfaceai/one-sdk@2.4.2, @superfaceai/parser@2.1.0)
- macOS
- OneSDK Beta0
- Node 18.13

**Comment by Jakub-Vacek** [comment]
@zdne I will add the message but I am still not able to replicate this (for me it works both locations). I believe that .mjs file gets executed but one of your locations has different setup (env, maybe node version). Could you provide me mjs file and map (in Slack)?

**Comment by Jakub-Vacek** [comment]
@kysely check if you have all required env variables

**Comment by Jakub-Vacek** [comment]
Also should be resolved in latest beta - you should get error when you are not in superface dir

**Comment by kysely** [comment]
Yes I'm actually pointing at whether that error is valid

**Comment by zdne** [comment]
Note the error is caused because of the missing `.env` file.

**Comment by kysely** [comment]
This already works and I think the issue can be closed now
