### ISSUE TITLE
[BUG] Regression: Notion, Slack, and Pipedrive

### ISSUE THREAD

**Issue by zdne** [superfaceai/cli#319]
The most basic usecases are no longer working with providers like Notion, Slack and Pipedrive. The algorithm refuses them as not possible to do with the given APIs which is not true.

## Expected Behavior
The profiles get created as before this was introduced.

## Current Behavior
```
% superface new pipedrive "list all customers"                                         
✔ Input arguments checked

⠙ Creating profile for your use case
✖ Failed to create profile: Described API is not able to fulfill your use case, please try to rephrase use case description or use different query. Reason: The provided API documentation is related to products and their followers, not customers.
```

## Steps to Reproduce
With the respective provider indexed, run one of the following:

```
superface new pipedrive "list all customers"
```

```
superface new notion "list all users"
```

```
superface new slack "list all users"
```

## Your Environment
- @superfaceai/cli/4.0.0-beta.5 darwin-x64 node-v18.13.0 (with @superfaceai/one-sdk@2.4.2, @superfaceai/parser@2.1.0)
- macOS
- OneSDK Beta0
- Node 18.13

**Comment by Jakub-Vacek** [comment]
Fixed in https://github.com/superfaceai/brain/pull/585

**Comment by kysely** [comment]
Fixed.
