### ISSUE TITLE
[BUG] CLI incorrectly reports missing arguments in the map step

### ISSUE THREAD

**Issue by zdne** [superfaceai/cli#340]
Running `sf map` command when I miss the provider argument prints me incorrect and confusing message

## Expected Behavior
The CLI reports that provider parameter is missing.

## Current Behavior
CLI reports that profile id is missing, suggests to submit it as a first parameter:

```
sf map organizations-management/get-organizations 
⠙ Loading profile
 ›   Error: ❌ Missing profile id. Please provide it as first argument.
```

## Steps to Reproduce
Run a map command, omit the provider id

## Your Environment
- macOS 13.4.1
- @superfaceai/cli/4.0.0 darwin-x64 node-v18.13.0

**Comment by Jakub-Vacek** [comment]
This is due to use of positional arguments - values are not tied to ids (provider name or profile id). In this case it should be addressed by error with message similar to:
```
Error: ❌ Missing provider name or profile id. Please provide provider name as first argument and profile id as second argument.
```
